services:
  # The container for the Web Application
  livrariaonline:
    image: ${DOCKER_REGISTRY-}livrariaonline
    build:
      context: .
      dockerfile: LivrariaOnline/Dockerfile
    environment:
          - ConnectionStrings__DefaultConnection=Server=SqlServerContainer;Database=LivrariaOnline;User Id=sa;Password=LivrariaXPTO123;Trust Server Certificate=True;
    depends_on:
        - SqlServerDB
  # The container for the database
  SqlServerDB:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:latest
    ports:
        - "8002:1433"
    environment:
        - "ACCEPT_EULA=Y"
        - "MSSQL_SA_PASSWORD=LivrariaXPTO123"
    volumes:
      - dbVolume:/var/opt/mssql

volumes:
  dbVolume:
      